import argparse
import hashlib
import json
import os
from pathlib import Path


def _load_config(path: str) -> dict:
    if not path:
        return {}
    try:
        p = Path(path)
        if not p.exists():
            return {}
        data = json.loads(p.read_text("utf-8"))
        return data if isinstance(data, dict) else {}
    except Exception:
        return {}


def _derive_flag(seed: str, prefix: str) -> str:
    digest = hashlib.sha256(seed.encode("utf-8")).hexdigest()[:24]
    prefix = prefix.strip() if prefix else "FLAG"
    return f"{prefix}{{{digest}}}"


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate a basic artifact and flag.")
    parser.add_argument("--config", default=os.environ.get("CONFIG_PATH", ""))
    parser.add_argument("--seed", default=os.environ.get("SEED", ""))
    parser.add_argument("--flag-prefix", default=os.environ.get("FLAG_PREFIX", "FLAG"))
    parser.add_argument("--out-dir", default=os.environ.get("OUT_DIR", "out"))
    args = parser.parse_args()

    cfg = _load_config(args.config)
    if not args.seed:
        args.seed = str(cfg.get("seed") or "")
    if args.flag_prefix == "FLAG":
        args.flag_prefix = str(cfg.get("flag_prefix") or cfg.get("flag-prefix") or args.flag_prefix)

    if not args.seed:
        raise SystemExit("Missing --seed (or SEED env var)")

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    flag_value = _derive_flag(args.seed, args.flag_prefix)

    artifact_path = out_dir / "artifact.txt"
    artifact_path.write_text(
        "This file is an artifact generated by a Flag-Generator.\n"
        "It is intended to be used as part of a challenge.\n\n"
        f"seed={args.seed}\n"
        f"hint=SHA256(seed) truncated\n",
        encoding="utf-8",
    )

    outputs = {
        "generator_id": "gen.py.basic_artifact",
        "outputs": {
            "flag": flag_value,
            "artifact_path": str(artifact_path.resolve()),
        },
    }

    outputs_path = out_dir / "outputs.json"
    outputs_path.write_text(json.dumps(outputs, indent=2) + "\n", encoding="utf-8")

    print(json.dumps(outputs, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
